feat: music player
starsJuly/sui-song-list pull request #3
Opened 2024-07-30 07:54 UTC by SuperChipsAhoy

This PR introduces a music player that plays audio directly on the webpage and integrates with media session API. 
This PR also includes the following changes:
- Many elements in the original playlist were blank; this PR moves these items to the first column.
- It adds a badge for those entries with our cute long-tailed bushtit performance recording to make it more noticeable. The theme is configurable in `tailwind.config.js`
- It converts some styles to use Tailwind CSS.

2024-07-30 11:01 UTC, SuperChipsAhoy commented
After [ced628d](https://github.com/starsJuly/sui-song-list/pull/3/commits/ced628d0d56b39cab1fd30d0678216d86382cb2d) `SongList.compont.jsx` now fully embraces Tailwind CSS.

2024-07-30 17:10 UTC, starsJuly requested changes

2024-07-30 17:10 UTC, starsJuly commented on components/SongList.component.jsx
When the screen size is smaller, the labels in the song list go outside their boxes.
![1722358163095](https://github.com/user-attachments/assets/4882b90f-9be6-486c-ad71-1cc4f28b7d1c)

2024-07-30 17:10 UTC, starsJuly commented on pages/index.js
The callback functions  always have no changes except for their closures. To avoid updates frequently, I merge all callbacks' closures into one object called 'EffThis'. It is experimental for performance optimization. Just like,
```
const [ currently_playing, set_currently_playing ] = EffThis.currently_playing = useState(-1);

useEffect(() => {
    EffThis.set_current_album = (album) => EffThis.current_album = album;
    EffThis.play_music_at = (idx) => eff_set(EffThis, 'currently_playing', idx);
}, [ EffThis ])

```

2024-07-30 17:10 UTC, starsJuly commented on tailwind.config.js
Great. And we may support more theme styles and more customizable theme properties in the future.

2024-07-30 23:49 UTC, SuperChipsAhoy commented on components/SongList.component.jsx
Fixed in [4ded330](https://github.com/starsJuly/sui-song-list/pull/3/commits/4ded330c4ffb18487a5c6316f528691957ad5f0f) and [559523b](https://github.com/starsJuly/sui-song-list/pull/3/commits/559523b6dcf31c4271e6d4df44fefc4e9a22f6b9).

2024-07-30 23:50 UTC, SuperChipsAhoy commented on pages/index.js
Changed in [b7316bf](https://github.com/starsJuly/sui-song-list/pull/3/commits/b7316bff4309576b96345dc591ed8b98f2c107b9).

2024-07-31 02:06 UTC, KpwnZ commented
We can merge it now I guess?

2024-07-31 14:22 UTC, starsJuly approved these changes

2024-07-31 14:48 UTC, KpwnZ approved these changes

2024-07-31 14:54 UTC, merged